name: Angular CI

on: 
    push:
        branches: 
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Descargar repositorio
              uses: actions/checkout@v4

            - name: Configurar/Instalar Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22
            
            - name: Instalar Dependencias
              run: nmp install
              
            - name: Ejecutar pruebas
              run: nmp run test -- --run
            
            - name: Generar Build
              run: nmp run build
